djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

from web_scrapping import web_scrapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('category.urls')),
    path('', include('product.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
    path('web-scrapping/', web_scrapp.get_data_web_scrapping, name='web_scrapping'),
    path('rest-api/', include('rest_framework.urls'))
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('index/', views.index, name='index1'),
    path('all-students/', views.students, name='all_stundents'),
    path('all-brands/', views.brands, name='all_brands'),
    path('', views.HomeTemplateView.as_view(), name='homepage')
]

category/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=400)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

product/models.py
from django.db import models

from category.models import Category


class Product(models.Model):
    stock_choices = (('yes', 'Yes'), ('no', 'No'))

    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(max_length=400, null=True, blank=True)
    active = models.BooleanField(default=True)
    price = models.IntegerField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    is_stock = models.CharField(max_length=10, choices=stock_choices, null=True, blank=True)
    release = models.DateField(null=True, blank=True)
    # email = models.EmailField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='media/', null=True, blank=True)

    def __str__(self):
        return self.name

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">


</head>
<body>
{% include 'menu.html' %}
{% block content %}
{% endblock %}

</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

</html>

templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Django Project</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
                </li>

                {% if request.user.is_authenticated %}
                    {#                    and request.user.is_superuser#}

                    <li class="nav-item dropdown">

                        {% if perms.category.view_category %}
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Category
                            </a>
                        {% endif %}

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                            {% if perms.category.add_category %}
                                <li><a class="dropdown-item" href="{% url 'create_category' %}">Create a new
                                    category</a>
                                </li>
                            {% endif %}

                            {% if perms.category.view_category %}
                                <li><a class="dropdown-item" href="{% url 'list_of_categories' %}">List of
                                    categories</a>
                                </li>
                            {% endif %}

                            {% if perms.category.import_category %}
                            <li>
                                <a class="dropdown-item" href="{% url 'import_data' %}">Import data by XLS</a>
                            </li>
                            {% endif %}

                            <li>
                                <a class="dropdown-item" href="{% url 'update_data' %}">Update category</a>
                            </li>

                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>

                    </li>

                    <li class="nav-item dropdown">

                        {% if perms.product.view_product %}
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Products
                            </a>
                        {% endif %}

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if perms.product.add_product %}
                                <li><a class="dropdown-item" href="{% url 'create_product' %}">Create a new product</a>
                                </li>
                            {% endif %}

                            {% if perms.product.view_product %}
                                <li><a class="dropdown-item" href="{% url 'list_of_products' %}">List of products</a>
                                </li>
                            {% endif %}

                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>

                        </ul>
                    </li>

                    <li class="nav-item dropdown">

                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            All categories
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for category in allcategories %}
                                <li><a class="dropdown-item"
                                       href="{% url 'products_per_category' category.id %}">{{ category.name }}</a>
                                </li>
                            {% endfor %}

                        </ul>
                    </li>

                {% endif %}

            </ul>

            {% if request.user.is_authenticated %}

                <a href="{% url 'logout' %}" class="btn btn-danger">Logout {{ request.user.username }}</a>

            {% else %}

                <a href="{% url 'create_user' %}" class="btn btn-secondary">Sign up</a>
                <a href="{% url 'login' %}" class="btn btn-success">Login</a>

            {% endif %}

        </div>
    </div>
</nav>